if(NOT DEFINED SCMDC OR NOT DEFINED SOURCE OR NOT DEFINED WORKDIR)
    message(FATAL_ERROR "check_volatile_noopt_shape.cmake missing required -D argument")
endif()
file(REMOVE_RECURSE "${WORKDIR}")
file(MAKE_DIRECTORY "${WORKDIR}")
set(out "${WORKDIR}/volatile_noopt.cfg")
execute_process(COMMAND "${SCMDC}" "${SOURCE}" -o "${out}" --console-mode sync
    WORKING_DIRECTORY "${WORKDIR}"
    RESULT_VARIABLE rc OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr)
if(NOT rc EQUAL 0)
    message(FATAL_ERROR "compile failed (${rc})\n${stdout}\n${stderr}")
endif()
file(GLOB lazy_pages "${WORKDIR}/volatile_noopt.lazy/f0000/*.cfg")
if(NOT lazy_pages)
    message(FATAL_ERROR "@noopt function lazy body not found")
endif()
set(lazy_text "")
foreach(p IN LISTS lazy_pages)
    file(READ "${p}" t)
    string(APPEND lazy_text "${t}")
endforeach()
if(NOT lazy_text MATCHES "__scmd_l[0-9]+")
    message(FATAL_ERROR "@noopt body lost stable internal aliases; optimizer appears to have renamed/fused it\n${lazy_text}")
endif()
file(GLOB eager_pages "${WORKDIR}/volatile_noopt.pages/*.cfg")
set(eager_text "")
foreach(p IN LISTS eager_pages)
    file(READ "${p}" t)
    string(APPEND eager_text "${t}")
endforeach()
foreach(bit RANGE 0 7)
    if(NOT eager_text MATCHES "__scmd_g0_b${bit}")
        message(FATAL_ERROR "volatile u8 storage bit ${bit} missing")
    endif()
endforeach()
