if(NOT DEFINED SCMDC OR NOT DEFINED SCMDSIM OR NOT DEFINED SOURCE OR NOT DEFINED OUTDIR)
    message(FATAL_ERROR "SCMDC, SCMDSIM, SOURCE and OUTDIR are required")
endif()

function(check_one suffix extra_arg)
    set(dir "${OUTDIR}/${suffix}")
    file(REMOVE_RECURSE "${dir}")
    file(MAKE_DIRECTORY "${dir}")
    set(outcfg "${dir}/output.cfg")
    if(extra_arg STREQUAL "")
        execute_process(COMMAND "${SCMDC}" "${SOURCE}" -o "${outcfg}" --console-mode sync RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
    else()
        execute_process(COMMAND "${SCMDC}" "${SOURCE}" -o "${outcfg}" --console-mode sync "${extra_arg}" RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
    endif()
    if(NOT rc EQUAL 0)
        message(FATAL_ERROR "lazy compile ${suffix} failed (${rc})\n${out}\n${err}")
    endif()
    if(NOT EXISTS "${dir}/output.lazy/f0000/000.cfg")
        message(FATAL_ERROR "helper lazy module was not emitted (${suffix})")
    endif()
    file(GLOB eager_pages "${dir}/output.pages/*.cfg")
    set(eager "")
    foreach(page IN LISTS eager_pages)
        file(READ "${page}" text)
        string(APPEND eager "${text}")
    endforeach()
    if(eager MATCHES "LAZY_HELPER_PASS")
        message(FATAL_ERROR "helper implementation leaked into eager pages (${suffix})")
    endif()
    if(NOT eager MATCHES "alias __scmd_fn0 \"exec output.lazy/f0000/000.cfg\"")
        message(FATAL_ERROR "mandatory helper load stub missing (${suffix})\n${eager}")
    endif()
    if(NOT eager MATCHES "alias __scmd_fn1 \"exec output.lazy/f0001/000.cfg\"")
        message(FATAL_ERROR "mandatory screen load stub missing (${suffix})\n${eager}")
    endif()
    file(GLOB lazy_pages "${dir}/output.lazy/f0000/*.cfg")
    set(lazy "")
    foreach(page IN LISTS lazy_pages)
        file(READ "${page}" text)
        string(APPEND lazy "${text}")
    endforeach()
    if(NOT lazy MATCHES "LAZY_HELPER_PASS")
        message(FATAL_ERROR "helper implementation missing from lazy module (${suffix})")
    endif()
    file(GLOB screen_pages "${dir}/output.lazy/f0001/*.cfg")
    set(screen_lazy "")
    foreach(page IN LISTS screen_pages)
        file(READ "${page}" text)
        string(APPEND screen_lazy "${text}")
    endforeach()
    if(NOT screen_lazy MATCHES "LAZY_HELPER_PASS" OR NOT screen_lazy MATCHES "LAZY_SCREEN_BEGIN")
        message(FATAL_ERROR "stateless helper was not co-loaded with caller (${suffix})")
    endif()
    execute_process(COMMAND "${SCMDSIM}" "${dir}" --exec output --no-interactive --no-ansi --max-commands 100000 RESULT_VARIABLE sim_rc OUTPUT_VARIABLE sim_out ERROR_VARIABLE sim_err)
    if(NOT sim_rc EQUAL 0 OR NOT sim_out MATCHES "LAZY_HELPER_PASS" OR NOT sim_out MATCHES "LAZY_SCREEN_END")
        message(FATAL_ERROR "lazy execution failed (${suffix}, ${sim_rc})\n${sim_out}\n${sim_err}")
    endif()
    if(sim_out MATCHES "execing output.lazy/f0000/000.cfg")
        message(FATAL_ERROR "nested helper caused a mid-function lazy exec (${suffix})\n${sim_out}")
    endif()
endfunction()

check_one(opt "")
check_one(noopt "--no-opt")
