if(NOT DEFINED SCMDC OR NOT DEFINED SCMDSIM OR NOT DEFINED EXPECTED)
    message(FATAL_ERROR "check_versions.cmake missing required -D argument")
endif()
execute_process(COMMAND "${SCMDC}" --version RESULT_VARIABLE c_rc OUTPUT_VARIABLE c_out ERROR_VARIABLE c_err OUTPUT_STRIP_TRAILING_WHITESPACE)
execute_process(COMMAND "${SCMDSIM}" --version RESULT_VARIABLE s_rc OUTPUT_VARIABLE s_out ERROR_VARIABLE s_err OUTPUT_STRIP_TRAILING_WHITESPACE)
if(NOT c_rc EQUAL 0 OR NOT s_rc EQUAL 0)
    message(FATAL_ERROR "version command failed\nscmdc: ${c_rc} ${c_err}\nscmdsim: ${s_rc} ${s_err}")
endif()
if(NOT c_out STREQUAL EXPECTED OR NOT s_out STREQUAL EXPECTED)
    message(FATAL_ERROR "version mismatch: expected=${EXPECTED} scmdc=${c_out} scmdsim=${s_out}")
endif()
