if(NOT DEFINED SCMDC OR NOT DEFINED SCMDSIM OR NOT DEFINED SOURCE OR NOT DEFINED OUTDIR)
    message(FATAL_ERROR "SCMDC, SCMDSIM, SOURCE and OUTDIR are required")
endif()
file(REMOVE_RECURSE "${OUTDIR}")
file(MAKE_DIRECTORY "${OUTDIR}")
set(OUTCFG "${OUTDIR}/resident.cfg")
execute_process(COMMAND "${SCMDC}" "${SOURCE}" -o "${OUTCFG}" --console-mode sync RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
if(NOT rc EQUAL 0)
    message(FATAL_ERROR "compile failed (${rc})\n${out}\n${err}")
endif()
file(GLOB_RECURSE cfgs "${OUTDIR}/*.cfg")
set(all "")
foreach(f IN LISTS cfgs)
    file(READ "${f}" t)
    string(APPEND all "\n${t}")
endforeach()
if(NOT all MATCHES "alias resident_ping ")
    message(FATAL_ERROR "export resident function has no stable public alias")
endif()
if(all MATCHES "lazy/f0000")
    message(FATAL_ERROR "resident function was emitted as demand-loaded code")
endif()
execute_process(COMMAND "${SCMDSIM}" "${OUTDIR}" --exec resident --no-interactive --no-engine-messages --no-ansi RESULT_VARIABLE src OUTPUT_VARIABLE sout ERROR_VARIABLE serr)
if(NOT src EQUAL 0 OR NOT sout MATCHES "RESIDENT_OK")
    message(FATAL_ERROR "resident simulation failed (${src})\n${sout}\n${serr}")
endif()
